---
apiVersion: v1
kind: Service
metadata:
  name: nginx-m
spec:
  selector:
    app: nginx
  ports:
    name: nginx-s
    port: 80
    protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-C
spec:
  selector:
    app: nginx-color
  ports:
    name: nginx-C
    port: 80
    protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-m
spec:
  selector:
    app: nginx-m
  ports:
    name: nginx-m
    port: 80
    protocol: TCP


  
    